export enum ApiUrls {
  baseApiUrl = "https://192.168.2.4/abkkpss/",
  getCommitee = "/getCommitee",
  getCurrentUser = "/getCurrentUser",
  getFamilyTree = "/getFamilyTree",
  getFirms = "/getFirms",
  getMembers = "/getMembers",
  getUsers = "/getUsers",
  getZones = "/getZones",
  getMemberForDirectoryList = "/getMemberForDirectoryList",
  login = "/authAuthenticate",
  logout = "/authLogout",
  performOperation = "/performOperation",
  updateUserType = "/updateUserType",
  uploadFirmProfileImage = "/uploadFirmProfileImage",
  uploadMemberProfileImage = "/uploadMemberProfileImage",
}
